function dict = TCAVConfig()

            dict = containers.Map();

            % Add key-value pairs
            dict('20') = { ...
                'TCAV:LI20:2400:C_1_TCTL'; ...
                'TCAV:LI20:2400:PDES'; ...
                'TCAV:LI20:2400:ADES'; ...
                'TCAV:LI20:2400:P'; ...
                'TCAV:LI20:2400:A'; ...
                'TCAV_LI20_PDES'
            };
            dict('10') = {
                'KLYS:LI10:51:TRIGMODE'; ...
                'KLYS:LI10:51:PDES'; ...
                'KLYS:LI10:51:ADES'; ...
                'KLYS:LI10:51:PHAS'; ... % 'KLYS:LI10:51:PACT05'
                'KLYS:LI10:51:AMPL'; ... % 'KLYS:LI10:51:POWER_W0CH0'
                'TCAV_LI10_PDES'
                
                
            };

end